In [1]:
import numpy as np

# Q1 - Write a NumPy program to create an array of all even integers from 30 to 70.

In [2]:
numbers = np.arange(30, 71)
even_numbers = numbers[numbers % 2 == 0]
print(even_numbers)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


# Q2 - Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [6]:
random_numbers = np.random.randn(15)
print(random_numbers)

[ 0.90149578  1.05117896 -0.72196204  0.61601408  0.05508368  1.65829098
 -0.98105537 -0.11940405 -0.21612102 -1.29703477 -0.18717116 -0.12816475
 -0.13020322  0.26835751  1.12422289]


# Q3 - How to compute the cross-product of two matrices in NumPy?

In [9]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
matrix2 = np.array([[7, 8, 9],
                    [10, 11, 12]])
cross_product = np.cross(matrix1, matrix2)
                        
print("Cross-product of the matrices:")
print(cross_product)

Cross-product of the matrices:
[[-6 12 -6]
 [-6 12 -6]]


# Q4 - How to compute the determinant of an array using NumPy?

In [10]:
matrix = np.array([[1, 2],
                   [3, 4]])

determinant = np.linalg.det(matrix)

print("Determinant of the matrix:", determinant)

Determinant of the matrix: -2.0000000000000004


# Q5 - How to create a 3x3x3 array with random values using NumPy?

In [11]:
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.82607896 0.58340975 0.63660101]
  [0.20682609 0.61144505 0.74531214]
  [0.9604921  0.92690339 0.42679169]]

 [[0.65364476 0.19681113 0.92276109]
  [0.71852807 0.52163564 0.66080668]
  [0.75340643 0.46521295 0.39016541]]

 [[0.31937497 0.0824355  0.57692793]
  [0.728694   0.097673   0.13332884]
  [0.36587371 0.91222612 0.94230307]]]


# Q6 - How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?

In [12]:
random_array = np.random.rand(5, 5)
min_value = random_array.min()
max_value = random_array.max()

print("\nMinimum value:", min_value)
print("Maximum value:", max_value)



Minimum value: 0.006218464036180094
Maximum value: 0.9989075101788742


# Q7 - How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?

In [13]:
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

mean = np.mean(array, axis=1)
std_dev = np.std(array, axis=1)
variance = np.var(array, axis=1)

print("Mean along the second axis:", mean)
print("Standard deviation along the second axis:", std_dev)
print("Variance along the second axis:", variance)


Mean along the second axis: [2. 5.]
Standard deviation along the second axis: [0.81649658 0.81649658]
Variance along the second axis: [0.66666667 0.66666667]
